package com.test.dao;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.test.model.Euser;
import com.test.model.EuserExample;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EuserDAOImpl extends SqlMapDaoTemplate implements EuserDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public EuserDAOImpl(DaoManager daoManager) {
        super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public void insert(Euser record) {
        insert("euser.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public List selectByExample(EuserExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = queryForList("euser.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public List selectByExample(EuserExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public int deleteByExample(EuserExample example) {
        int rows = delete("euser.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private Map getuidExampleParms(EuserExample example) {
        Map parms = new HashMap();
        switch (example.getUid_Indicator()) {
        case EuserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_NULL", "Y");
            } else {
                parms.put("AND_uid_NULL", "Y");
            }
            break;
        case EuserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_NOT_NULL", "Y");
            } else {
                parms.put("AND_uid_NOT_NULL", "Y");
            }
            break;
        case EuserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_EQUALS", "Y");
            } else {
                parms.put("AND_uid_EQUALS", "Y");
            }
            parms.put("uid", example.getUid());
            break;
        case EuserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_uid_NOT_EQUALS", "Y");
            }
            parms.put("uid", example.getUid());
            break;
        case EuserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_GT", "Y");
            } else {
                parms.put("AND_uid_GT", "Y");
            }
            parms.put("uid", example.getUid());
            break;
        case EuserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_GE", "Y");
            } else {
                parms.put("AND_uid_GE", "Y");
            }
            parms.put("uid", example.getUid());
            break;
        case EuserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_LT", "Y");
            } else {
                parms.put("AND_uid_LT", "Y");
            }
            parms.put("uid", example.getUid());
            break;
        case EuserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_uid_LE", "Y");
            } else {
                parms.put("AND_uid_LE", "Y");
            }
            parms.put("uid", example.getUid());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private Map getenameExampleParms(EuserExample example) {
        Map parms = new HashMap();
        switch (example.getName_Indicator()) {
        case EuserExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_NULL", "Y");
            } else {
                parms.put("AND_ename_NULL", "Y");
            }
            break;
        case EuserExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_NOT_NULL", "Y");
            } else {
                parms.put("AND_ename_NOT_NULL", "Y");
            }
            break;
        case EuserExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_EQUALS", "Y");
            } else {
                parms.put("AND_ename_EQUALS", "Y");
            }
            parms.put("name", example.getName());
            break;
        case EuserExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ename_NOT_EQUALS", "Y");
            }
            parms.put("name", example.getName());
            break;
        case EuserExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_GT", "Y");
            } else {
                parms.put("AND_ename_GT", "Y");
            }
            parms.put("name", example.getName());
            break;
        case EuserExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_GE", "Y");
            } else {
                parms.put("AND_ename_GE", "Y");
            }
            parms.put("name", example.getName());
            break;
        case EuserExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_LT", "Y");
            } else {
                parms.put("AND_ename_LT", "Y");
            }
            parms.put("name", example.getName());
            break;
        case EuserExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_LE", "Y");
            } else {
                parms.put("AND_ename_LE", "Y");
            }
            parms.put("name", example.getName());
            break;
        case EuserExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ename_LIKE", "Y");
            } else {
                parms.put("AND_ename_LIKE", "Y");
            }
            parms.put("name", example.getName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private Map getExampleParms(EuserExample example) {
        Map parms = new HashMap();
        parms.putAll(getuidExampleParms(example));
        parms.putAll(getenameExampleParms(example));
        return parms;
    }
}