package com.test.model;

public class EuserExample extends Euser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private int uid_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private int name_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public int getUid_Indicator() {
        return uid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public void setUid_Indicator(int uid_Indicator) {
        this.uid_Indicator = uid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public int getName_Indicator() {
        return name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table euser
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public void setName_Indicator(int name_Indicator) {
        this.name_Indicator = name_Indicator;
    }
}