package com.test.model;

public class Euser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column euser.uid
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column euser.ename
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    private String name;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column euser.uid
     *
     * @return the value of euser.uid
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column euser.uid
     *
     * @param uid the value for euser.uid
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column euser.ename
     *
     * @return the value of euser.ename
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column euser.ename
     *
     * @param name the value for euser.ename
     *
     * @abatorgenerated Mon Nov 02 15:38:38 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}